# syntax=docker/dockerfile:1

FROM ghcr.io/astral-sh/uv:0.12.19 AS uv

FROM python:3.14.7-slim-trixie

RUN apt-get update \
&& apt-get install -y --no-install-recommends git \
&& rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    PATH="/app/.venv/bin:${PATH}"

WORKDIR /app

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=uv /uv /uvx /usr/local/bin/

# Copy dependency metadata first for build caching.
COPY pyproject.toml ./

# Resolve and install production dependencies.
# Do not use --locked because this project has no uv.lock.
RUN uv sync \
    --no-dev \
    --no-install-project

# Copy source code and files generated by the setup scripts.
COPY . .

RUN groupadd --gid 1000 fishingbucket \
    && useradd \
        --uid 1000 \
        --gid fishingbucket \
        --create-home \
        --no-log-init \
        fishingbucket \
    && chown -R fishingbucket:fishingbucket /app

USER fishingbucket

CMD ["python", "/app/main.py", "/app/config/config.json"]